name: 'uos-action'
author: 'liyizhuang <lihaha1024@gmail.com>'
description: 'upload object storage'
branding:
  icon: 'upload-cloud'
  color: 'white'
inputs:
  cloudType:
    description: 'Cloud type'
    required: false
    default: 'cos'
  secretId:
    description: 'Secret id'
    required: true
  secretKey:
    description: 'Secret key'
    required: true
  bucket:
    description: 'Bucket name'
    required: true
  region:
    description: 'Bucket region'
    required: true
  localPath:
    description: 'Local path'
    required: true
  remotePath:
    description: 'Remote path'
    required: false
    default: '/'
  uploadSuffix:
    description: 'Upload order suffix'
    required: false
  cdnDomain:
    description: 'CDN domain'
    required: false
    default: ''
  cdnRefresh:
    description: 'CDN refresh'
    required: false
    default: false
  cdnRefreshSuffix:
    description: 'CDN refresh suffix'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
