name: deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: deploy
        uses: lihawhaw/uos-action@v0.1.0
        with:
          secretId: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secretKey: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          bucket: ${{ secrets.COS_BUCKET }}
          region: ${{ secrets.COS_REGION }}
          localPath: '.github'
          remotePath: '/'
